### ISSUE TITLE
So u only open source the vm?

### ISSUE THREAD

**Issue by SoilZhu** [Gandi-IDE/scratch-vm#1]
I noticed that you only open the vm’s source. So when you will open other sources?

The License doesn't allow you to privatize the codes, I wish you have already known that.

**Comment by sylarhcn** [comment]
hi, soilland
CCW scratch-gui is base on https://github.com/LLK/scratch-gui which licensed under BSD 3-Clause "New" or "Revised" License. it's not force open source.
some scratch lib/project which CCW modified already open source in this group.
all other scratch lib/project used in CCW are original version.

we dont open source current GUI cuz' the code mess up and will have security risk.
in long term, we have a plan to rewrite all gui, this new project will be open source when it's done.

if you want more info or disscussion, we have a open online meeting tomorrow night, you are welcome to link in
see [如何参与 CCW 圆桌会](https://ccw-site.feishu.cn/docs/doccnsmeoPxtuKwke4LOO4YpbTb)

**Comment by guio13233** [comment]
> hi, soilland CCW scratch-gui is base on https://github.com/LLK/scratch-gui which licensed under BSD 3-Clause "New" or "Revised" License. it's not force open source. some scratch lib/project which CCW modified already open source in this group. all other scratch lib/project used in CCW are original version.
> 
> we dont open source current GUI cuz' the code mess up and will have security risk. in long term, we have a plan to rewrite all gui, this new project will be open source when it's done.
> 
> if you want more info or disscussion, we have a open online meeting tomorrow night, you are welcome to link in see [如何参与 CCW 圆桌会](https://ccw-site.feishu.cn/docs/doccnsmeoPxtuKwke4LOO4YpbTb)

can i dm you for the gui source code?
